blank_issues_enabled: true
contact_links:
  - name: UNICORN Devs Chat
    url: https://t.me/unicorndevs
    about: Chat to us about the UNICORN Binance REST API and ask general questions.
  - name: UNICORN Binance REST API Discussions
    url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-rest-api/discussions
    about: Ask general questions.
  - name: UNICORN Binance REST API documentation
    url: https://unicorn-binance-rest-api.docs.lucit.tech/
    about: The complete UNICORN Binance REST API documentation.
